[package]
name = "p4-farm-nft"
version = "1.0.0"
authors = [""]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "*"
uint = { version = "0.9.0", default-features = false }
near-sdk = "^4.1"
near-contract-standards = "^4.1"
p3-lib = { path = "../p3-lib" }
